### PR TITLE
[MRG] Improve logging

### LINKED ISSUE #44: Improve logging
I realise now this is super important. If people email in when the tool crashes, there might not be much to go on. Need to be able to request logs.

### PR DESCRIPTION
**Pull request by shuttle1987**
Will close #44 

One thing I noticed is that in run.py there is a large amount of print statements and some logging code related to tensorflow commented out, was run.py previously supposed to be invoked as a command line script? Is this still a use case?

### CODE REVIEW

**Comment by shuttle1987** [comment]
This needs a bit of verification that it all works when used but should otherwise be in a state to merge.

**Comment by oadams** [comment]
Cool, looks good!

Run wasn't run as a script, but almost. It had functions I'd call from an interpreter to run experiments. Most of the unused ones have been removed. I'll add logger calls for the relevant functions in run.py and remove the no-longer relevant ones. I'll also rename the module.

Can you confirm that the new logging calls that are being covered by existing tests are printed to the log file?

This is good, but I'm wary of merging into master until the added lines have been tested. Which prompts me to make a new issue for you to work on while the GUI thing is sorted.

**Comment by shuttle1987** [comment]
For the most part the reason I have left the `[WIP]` here is because I haven't run this code from code external to the project, the test cases seem to be fine but that's something that I'll need to check.

I did see a fairly substantial problem just now, we were setting the logger with `fileConfig` without parameters which due to backwards compatibility disables any previous loggers.

But really there's another point that has to be dealt with, seeing as we are not running persephone as a script we shouldn't be touching the logging configuration at all, this should be up to those who are using the library to do from their own code. Note that if we do make script entry points then we will need to set up logging again.

**Comment by shuttle1987** [comment]
I've just been running a test case with the tutorial data and so far this appears to work. The code I'm testing with is here: https://github.com/shuttle1987/persephone-logging-test/

**Comment by shuttle1987** [comment]
I think this is in a state where it can be merged. There's more that could be added to the logging for sure, but I think this is the sort of work we can do incrementally now that everything is set up.

**Comment by oadams** [comment]
Not sure why the travis-ci status check is still waiting.

**Comment by shuttle1987** [comment]
You should be able to restart the tests from the TravisCI web interface 

-------- Original message --------

**Pull request merged**
