### PR TITLE
[MRG] Feature config from file

### PR DESCRIPTION
**Pull request by shuttle1987**
Work to improve configuration of paths

### CODE REVIEW

**Comment by oadams** [comment]
Great, I'm keen on using configparser.

Perhaps its worth putting the KALDI_ROOT, OPENFST_BIN_PATH, FFMPEG_PATH, and SOX_PATH in there, defaulting to what's on the PATH.

**Comment by shuttle1987** [comment]
Considering that this project has some significant complexity with regards to paths and binaries used it's important to spend some time thinking about configuration management. Specifically there are a lot of situations where the path to a specific directory must be specified for loading of data. This previously resided in config.py which had a variety of hardcoded strings which were imported by other modules, here's a snippet that shows the general pattern:

Config.py: https://github.com/oadams/persephone/blob/56a22bfcf733dc54734927fbfa198a63c120db78/persephone/config.py
```python
# The directory where the preprocessed data will be held.
TGT_DIR = "./data"
# The path for experiments
EXP_DIR = "./exp"

# The path to the sox tool for converting NIST format to WAVs.
SOX_PATH = "/home/oadams/tools/sox-14.4.2/src/sox"
OPENFST_BIN_PATH = "/home/oadams/tools/openfst-1.6.2/src/bin"
FFMPEG_PATH = "/home/oadams/tools/ffmpeg-3.3/ffmpeg"
KALDI_ROOT = "/home/oadams/tools/kaldi"
```
Which is used in the dataset processing files such as Chatino:

https://github.com/oadams/persephone/blob/56a22bfcf733dc54734927fbfa198a63c120db78/persephone/datasets/chatino.py#L8
```python
from .. import config
from .. import corpus
from .. import feat_extract
from .. import utils

### Initialize path variables.###
# Path to unpreprocessed Chatino data from GORILLA.
ORG_DIR = config.CHATINO_DIR
# The directory for storing input features and targets.
TGT_DIR = os.path.join(config.TGT_DIR, "chatino")
ORG_WAV_DIR = os.path.join(ORG_DIR, "wav")
```
There's a variety of issues with this approach to configuration some of which only appear after you create an installable package. In a small project storing configuration as Python files directly in the source is usually fine because you are able to quickly edit those files. If however you are packaging an install your source files are no longer in the current working directory as they are installed into the Python site-packages directory. This makes a significant barrier to configuration changes for non-technical users as many people are unaware of how to edit those files. Not to mention that this would be a poor place to store configuration considering that multiple projects could use the same package if it was installed system wide (this type of general issue is why it is strongly advisable to use Python virtual environments for your projects as it makes your projects isolated from external changes like the one just mentioned). To resolve this issue it makes a lot of sense to read in some configuration from a file. Python supplies the ConfigParser in the standard library to help you do just this. Due to this being in the standard library this is often our preferred way of setting up a configuration from file system because it doesn't need to bring in any dependencies.

The other rather large issue is that the way in which the configuration was being used in other modules was creating a situation where module imports will fail if the paths are incorrect. This leads to some counterintuitive error stacktraces, if a path can't be found generating an ImportError is at best a bit misleading. But the bigger issue is that in this project users will often be analyzing one spoken language at a time, say that they are working on language A and supply the paths for language A only, then errors from not specifying the path for files for language B at module import time is an annoying restriction on the user, forcing a user to do exception handling on an import seems like something we should not require. It is far better if the import that requires the a missing data set fails at the time the code is executed as this will allow people to use only the modules that they need without needing to be concerned about how the internals of modules manage the paths.

https://github.com/oadams/persephone/blob/56a22bfcf733dc54734927fbfa198a63c120db78/persephone/datasets/chatino.py#L29
```python
PREFIXES = [os.path.splitext(fn)[0]
            for fn in os.listdir(ORG_TRANSCRIPT_DIR)
if fn.endswith(".txt")]
```
This is an example of something that is at the module level, `ORG_TRANSCRIPT_DIR` is constructed from a path defined in config.py and will therefore fail if that path has not been specified at the time of module import. The solution to this is to make sure that this code only executes when Chatino language is actually being processed, this will involve a refactor.

Similarly for the paths to binaries, you want to make sure you only have to specify the binaries that are actually being used. Defaulting to the system names probably makes sense with the option for the user to override that path with something that that specify themselves in the configuration file.

**Comment by shuttle1987** [comment]
I guess there's a few decisions to be made here and a bit more work to be done considering that there are still some hardcoded paths in other areas of the code such as https://github.com/oadams/persephone/blob/023dd141cfa218316c61e6fe470f82a4d44f8381/persephone/datasets/babel.py#L12-L16

**Comment by oadams** [comment]
For the record, just following up on this in writing based on our conversations relating to this that we've had in person or on the phone...

We're on the same page here regarding the lazy loading and I am on board with your original proposal of the ConfigParser. I'm wary of merging this PR as-is just on account of the changes to the code that calls the external dependencies. Perhaps we can just merge though since I plan on removing those dependencies soon, so it's not a big deal.

**Comment by shuttle1987** [comment]
Summarizing what I think the concern is, we decided that we wanted to have binaries be searched via the system path, but then later decided that it would be good if the user could override the path to the binary to be something that is not on the path. We could always just back out the changes to the calls to the binaries:

    -        args = [config.SOX_PATH, in_fn, out_fn, "trim", str(start_time), "=" + str(end_time)]
    +        args = ["sox", in_fn, out_fn, "trim", str(start_time), "=" + str(end_time)]

What I'm thinking is that we could create the paths as defaults in the config and then at the call sites it just calls whatever was passed in. Overriding the paths to something that's not on the system path would then be something the user would do via the config file. This would allow someone to specify an exact binary that they need and would work even if there is a binary of the same name already on the path. If you like this approach I'll make the necessary changes to this PR to make that happen.

**Comment by oadams** [comment]
Yes, all understood and that sounds perfect!

**Comment by shuttle1987** [comment]
I backed out the path changes and made everything accessible from the config file. There's still some hardcoded paths lurking around in the datasets directory, what should we do with those?

**Comment by oadams** [comment]
Nice! Those paths should probably get similar treatment, ideally. But I can merge this PR now and they can be done later since they're not public corpora anyway.

**Comment by shuttle1987** [comment]
Right now all the paths in dataset/na.py are fine but seeing as I don't have the visibility as to which of the other dataset files are in use (vs not in public use) I think you should merge as you see fit, the code should be fine to merge now.

**Pull request merged**
